services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: playarena
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./playarena-backend
    ports:
      - "3000:3000"
    env_file: ./playarena-backend/.env.docker
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./playarena-backend/prisma:/app/prisma

volumes:
  pgdata:
